name: "Reviewpad Action"
description: "Reviewpad Action automates pull requests workflows using the Reviewpad configuration located at reviewpad.yml"
branding:
  icon: "send"
  color: "blue"
inputs:
  event:
    description: "GitHub event"
    default: ${{ toJSON(github) }}
    required: false
runs:
  using: "docker"
  image: "docker://reviewpad/action:fc7fcf8b8154882ba8de0fd55ca1b39c40cbbb57"
