blank_issues_enabled: false
contact_links:
  - name: Reviewpad Discussions
    url: https://github.com/reviewpad/reviewpad/discussions
    about: Reviewpad discussions
  - name: Reviewpad Community Support
    url: https://reviewpad.com/discord
    about: Please ask and answer questions here.
  - name: Reviewpad Documentation 
    url: https://docs.reviewpad.com
    about: Please check out the documentation.

